### ISSUE TITLE
Přidání vylepšeného sosáče do seznamu doplnku

### ISSUE THREAD

**Issue by jondas** [kodi-czsk/repository#3]
Upravil jsem plugin sosac.ph tak aby mohl zobrazovat i filmy. Prosím o zařazení do repositáře.
Zde je: https://github.com/jondas/plugin.video.sosac.ph

**Comment by jondas** [comment]
PS: je odzkoušen a funkční

**Comment by Kuci** [comment]
Nechces spravit pull request ? Na to su totiz pull requesty.

**Comment by jondas** [comment]
No já si totiž nejsem jistý jak fungují ty submodules (přidání repozitare do repozitáře).

**Comment by Kuci** [comment]
Pull request by si mal poslat tam, kde si spravil zmenu. Takze [tu](https://github.com/kodi-czsk/plugin.video.tv.sosac.ph).

**Comment by lzoubek** [comment]
@jondas diky za prispevek - tvuj kod jsem otestoval a funguje skvele. Ono se pravdepodobne jedna o novy plugin (vsimnul jsem si, ze jsi zmenil addon id). Puvodne jsem mel v planu mit 2 nezavisle doplnky tv sosac a Movies Sosac, hlavni duvod byl ten, ze by mel kazdy addon vyhledavani - zase by to ale (aspon zpocatku) zmanemalo duplikaci kodu - nicmene to by slo resit presunem SosacContentProvideru do modulu stream.resolver.

Nechtel bys plugin predelat na Movies Sosac? Dat mu nejakou ikonu a pridal by se jako novy

**Comment by jondas** [comment]
No já jsem totiž měl ten movies sosáč hotový ještě předtím než jsem začal spojovat movies sosáč a tv sosáč 😀. Já jsem právě chtěl dát ty kódy dohromady aby když se jeden vylepší tak ať nezůstane druhý pozadu (roztříštěnost). 
S tím vyhledáváním si myslím, že pokud hledáš nějaký film tak ti to skoro vždy najde 0 seriálů se stejným jménem a naopak, takže by se daly vypsat všechny seriály a filmy za sebe.

**Comment by lzoubek** [comment]
ok, udelejme tedy novy plugin, ktery bude umet jak serialy tak filmy, vytvoril jsem repo https://github.com/kodi-czsk/plugin.video.sosac.ph Muzes prosim vytvorit pull request?

**Comment by lzoubek** [comment]
Diky za pull request, novy plugin jsem pridal do repa, trosku jsem mu zmenil ikonu.
