### ISSUE TITLE
sosac strankovanie

### ISSUE THREAD

**Issue by bbaronSVK** [kodi-czsk/repository#5]
neslo by spravit do sosaca strankovanie? Neviem ci len ja mam tak slaby komp, ale proste som sa nedostal k ziadnemu zoznamu filmov. Pripadne ak by sa dal dorobit zoznam poslednych pridanych filmov/serialov. Alebo este lepsie vlastne nastavenie pre "vyhladavanie" tak ako to ma uloz.to

**Comment by hektor-hdb** [comment]
sosac web uz tyden nefunguje

**Comment by hektor-hdb** [comment]
sosac uz tyden nefunguje

**Comment by lzoubek** [comment]
presun issue do pluginu https://github.com/kodi-czsk/plugin.video.sosac.ph/issues/8
